### ISSUE TITLE
Add program to find factorial of numbers .

### ISSUE THREAD

**Issue by KaushikiKrity** [kaushikikrityy/hello_C_language#10]
Take proper cases .

**Comment by palash211** [comment]
can I do it in python ??

**Comment by mayu12525** [comment]
I would like to work on this issue.

**Comment by Anurag-ak99** [comment]
hey @kaushikikrityy I would like to contribute on the issue.

**Comment by KaushikiKrity** [comment]
@Anurag-ak99 This issue has been solved you can take up some other issue.
