### ISSUE TITLE
Organized structure required.

### ISSUE THREAD

**Issue by mayu12525** [kaushikikrityy/hello_C_language#17]
<b>Description</b>
While going through repository i noticed that there is mixing of multiple language programs.It leads to confusion.

**Comment by mayu12525** [comment]
Guildeline: create organized file structure according to the programming languages.

<b>Would you like to work on the issue?</b>

I would work on the issue if no one else wants to do it

**Comment by KaushikiKrity** [comment]
@mayu12525 Yes I have been checking out the issue. But if  you would like  to work on the issue then  go ahead! 
I assign this to you.

**Comment by mayu12525** [comment]
> @mayu12525 Yes I have been checking out the issue. But if you would like to work on the issue then go ahead!
> I assign this to you.

@kaushikikrityy  assign me this issue. I will work on it.

**Comment by KaushikiKrity** [comment]
@mayu12525 please go ahead . Any query you can confirm. Thank you.

**Comment by mayu12525** [comment]
@kaushikikrityy ok

**Comment by mayu12525** [comment]
**Description**
I have created an Organized structure. I have separated CPP and c programs.
