### ISSUE TITLE
Add Some intermediate questions and there solutions.

### ISSUE THREAD

**Issue by KaushikiKrity** [kaushikikrityy/hello_C_language#20]
Try adding some good questions neither basic nor advanced in language C++ .

**Comment by mayu12525** [comment]
can we add here competitive programming questions and solutions?

**Comment by KaushikiKrity** [comment]
@mayu12525 yes sure !! But keep in mind the level should be intermediate.

**Comment by mayu12525** [comment]
@kaushikikrityy yes sure!!

**Comment by rahul975337** [comment]
can i make some contribution in this?

**Comment by shreyaraj13** [comment]
please assign this to me

**Comment by KaushikiKrity** [comment]
@rahul975337  @shreyaraj13 please go ahead.
