### ISSUE TITLE
Elaborate about concept of OOPs

### ISSUE THREAD

**Issue by KaushikiKrity** [kaushikikrityy/hello_C_language#30]
Make a document file in which you have to explain the concepts of oops. Like what is required to learn OOPs , Why is it essential.

**Comment by sanju6890** [comment]
I want to add some a section in the repository which will contain an introduction to STL and some important STL concepts.
Please confirm, If I can contribute or not.

**Comment by PardeepKumar816** [comment]
i can make a document file on oops ....should i?

**Comment by KaushikiKrity** [comment]
@pardeep596  Yes please go forward.

**Comment by KaushikiKrity** [comment]
> I want to add some a section in the repository which will contain an introduction to STL and some important STL concepts.
> Please confirm, If I can contribute or not.

yes sure please go ahead . #37

**Comment by sanju6890** [comment]
Hello @kaushikikrityy I want to contribute a cpp program on a very important STL concept **Vectors**.
Kindly confirm, if I can?

**Comment by KaushikiKrity** [comment]
> Hello @kaushikikrityy I want to contribute a cpp program on a very important STL concept **Vectors**.
> Kindly confirm, if I can?

sure.

**Comment by mayu12525** [comment]
@kaushikikrityy can u assign this issue to me?
