### ISSUE TITLE
Put the programs in their respective files.

### ISSUE THREAD

**Issue by KaushikiKrity** [kaushikikrityy/hello_C_language#36]
put programs in the respective folders. C programs in C files and Cpp programs in cpp file.

**Comment by PardeepKumar816** [comment]
can u assign this to me

**Comment by KaushikiKrity** [comment]
@mayu12525 this is assigned to you in case you don't want to take up inform .

**Comment by KaushikiKrity** [comment]
> can u assign this to me

actually This was earlier assigned to other person please look for some other issue. Thank you!

**Comment by mayu12525** [comment]
@kaushikikrityy I would like to work on this issue.

**Comment by KaushikiKrity** [comment]
@mayu12525  go ahead
