### ISSUE TITLE
STL concepts

### ISSUE THREAD

**Issue by sanju6890** [kaushikikrityy/hello_C_language#37]
It is very important to know about importance of STL usage. So, I wanted to add a section of it to your repository.

**Comment by KaushikiKrity** [comment]
@sanju6890  would you like to work on it ?

**Comment by sanju6890** [comment]
Yes, I want to work on it.

Thanks & Regards
Sanjay Kumar

**Comment by mayu12525** [comment]
I am also interested to solve this issue. can I solve this issue?
@kaushikikrityy can u assign this issue to me?

**Comment by KaushikiKrity** [comment]
> I am also interested to solve this issue. can I solve this issue?
> @kaushikikrityy can u assign this issue to me?

yes ! Go ahead!

**Comment by Piyush228** [comment]
I am also want to work on it and solve issue .
@kaushikikrityy  can u assign this issue to me?

**Comment by KaushikiKrity** [comment]
@Piyush228 @mayu12525 You both can add up to that!

**Comment by Piyush228** [comment]
can we add some pdf on stl 
I have good pdf

**Comment by mayu12525** [comment]
@Piyush228 yes sure..
