### ISSUE TITLE
Add some more programs in cpp.

### ISSUE THREAD

**Issue by mayu12525** [kaushikikrityy/hello_C_language#43]
**Description**

Add some more intermediate level CPP programs.

**Comment by KAbhijeet2105** [comment]
I would like to work on this.

**Comment by Piyush228** [comment]
i would like to add problem of DP and sliding window please assign me

**Comment by KAbhijeet2105** [comment]
@Piyush228 go ahead and add a variety of programs of intermediate level.

**Comment by KAbhijeet2105** [comment]
@kaushikikrityy @mayu12525 I suggest don't close this issue. Let the issue remain as it is so developers can add more programs.
just merge the PR's which resolves this issue.

**Comment by Piyush228** [comment]
I recently add HouseRobber.cpp DP problem please give a feedback so after that we will add more code

**Comment by sanju6890** [comment]
Hi @kaushikikrityy I also want to contribute some good Recursion Problems in C++.
Kindly assign this issue to me as well.
Thank you :)
Hope to hear from you soon, happy coding 👍

**Comment by KaushikiKrity** [comment]
> Hi @kaushikikrityy I also want to contribute some good Recursion Problems in C++.
> Kindly assign this issue to me as well.
> Thank you :)
> Hope to hear from you soon, happy coding 👍

go ahead!

**Comment by sanju6890** [comment]
🙋‍♂️Hello @kaushikikrityy 
I have made a pull request for the same i.e **Recursion problems in C++**. I have added a separate section for Recursion which contains some basic C++ programs using recursion.

These are the very good but basic C++ programs to understand the concept of  Recursion well.

Thank you!
Happy Coding :)
