### ISSUE TITLE
Add question  and solution of C++  including pointers.

### ISSUE THREAD

**Issue by KaushikiKrity** [kaushikikrityy/hello_C_language#5]
The question should be basic.

**Comment by cunning-weasel** [comment]
Happy to give this a shot @kaushikikrityy

**Comment by KaushikiKrity** [comment]
Go ahead !!

**Comment by RahulG606** [comment]
I can add these questions. Can you please assign it to me?
1. print a string in reverse using a pointer
2. find the factorial of a given number using pointers.

**Comment by KaushikiKrity** [comment]
Yes please go forward! @RahulG606

**Comment by Anurag-ak99** [comment]
is the issue still open? can I contribute in it.

**Comment by shreyaraj13** [comment]
kindly assign this issue to me

**Comment by KaushikiKrity** [comment]
@Anurag-ak99  @shreyaraj13  please go ahead.

**Comment by mayu12525** [comment]
@kaushikikrityy I would like to work on this issue.
