### ISSUE TITLE
Add a guide file to start learning C++ language.

### ISSUE THREAD

**Issue by KaushikiKrity** [kaushikikrityy/hello_C_language#7]
Add links , tutorials or some guide how to start C++ .
Also give a brief description to why this language is essential.
There is already a file existing you  can contribute to this issue but please make sure that there is a file hello_C_language/guide file to start learning C++ language. make sure you contribute under this . Try to add some additional information.

**Comment by NavyaIyanampudi** [comment]
Can I contribute?

**Comment by mayu12525** [comment]
I would like to work on this issue.

**Comment by KaushikiKrity** [comment]
@mayu12525 @NavyaIyanampudi  you both can contribute to this issue but please make sure that there is a file  _hello_C_language/guide file to start learning C++ language_. make sure you contribute under this . Try to add some additional information.

**Comment by NavyaIyanampudi** [comment]
yaeh okay

**Comment by mayu12525** [comment]
I have added the file and guidelines.

**Comment by mayu12525** [comment]
**Description**

I Have added some important links and video tutorials links to some pdf books for CPP and answer to why CPP is essential?
